# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - master
  paths:
   include:
     -  vsphere_packer_templates/*
 
schedules:
- cron: "0 1 * * 0"
  displayName: Weekly Sunday build
  branches:
    include:
    - master
  always: true
 
pool:
 
  name: Default
 
steps:
 
- task: CopyFiles@2
 
  displayName: 'Copy Packer Files to Artifacts'
 
  inputs:
 
    SourceFolder: vsphere_packer_templates
 
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
 
 
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: PackerConfig 